version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: chat-app-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpassword
      POSTGRES_DB: chatapp
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
